2023-05-04 01:20:15,707 ERROR: Exception on /auth/login [GET] [in C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Home\Flask\rr\app\auth\routes.py", line 30, in login
    return render_template('login.html', title='Sign In', form=form)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: login.html
2023-05-04 01:20:20,672 ERROR: Exception on /auth/login [GET] [in C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Home\Flask\rr\app\auth\routes.py", line 30, in login
    return render_template('login.html', title='Sign In', form=form)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: login.html
2023-05-04 01:24:53,073 INFO: RealtyRadar startup [in C:\Users\Home\Flask\rr\app\__init__.py:64]
2023-05-04 01:25:11,503 ERROR: Exception on /auth/login [GET] [in C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Home\Flask\rr\app\auth\routes.py", line 30, in login
    return render_template('auth/login.html', title='Sign In', form=form)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Home\Flask\rr\app\templates\auth\login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Home\Flask\rr\app\templates\base.html", line 2, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block 'body'
    {% block navbar %}
  File "C:\Users\Home\Flask\rr\app\templates\base.html", line 11, in block 'navbar'
    <a class="blog-nav-item" href="{{ url_for('index') }}" }}>Home</a>
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2023-05-04 01:40:26,284 INFO: RealtyRadar startup [in C:\Users\Home\Flask\rr\app\__init__.py:64]
2023-05-04 01:40:49,728 ERROR: Exception on / [GET] [in C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Home\Flask\rr\app\main\routes.py", line 20, in index
    form = PostForm()
NameError: name 'PostForm' is not defined
2023-05-04 01:44:04,173 INFO: RealtyRadar startup [in C:\Users\Home\Flask\rr\app\__init__.py:64]
2023-05-04 01:44:13,370 ERROR: Exception on / [GET] [in C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Home\Flask\rr\app\main\routes.py", line 28, in index
    posts = current_user.followed_posts().paginate(page=page, per_page=current_app.config['POSTS_PER_PAGE'], error_out=False)
NameError: name 'current_app' is not defined
2023-05-04 01:48:34,093 INFO: RealtyRadar startup [in C:\Users\Home\Flask\rr\app\__init__.py:64]
2023-05-05 02:59:39,985 INFO: RealtyRadar startup [in C:\Users\Home\Flask\rr\app\__init__.py:64]
