2023-05-05 02:59:47,650 ERROR: Exception on /auth/login [GET] [in C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Home\Flask\rr\app\auth\routes.py", line 30, in login
    return render_template('login.html', title='Sign In', form=form)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Home\Flask\rr\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Home\Flask\rr\app\templates\base.html", line 2, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "C:\Users\Home\Flask\rr\app\templates\login.html", line 28, in block 'content'
    <a href="{{ url_for('reset_password_request') }}">Click to Reset!</a>
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'auth.reset_password_request' instead?
2023-05-05 23:29:54,472 INFO: RealtyRadar startup [in C:\Users\Home\Flask\rr\app\__init__.py:64]
2023-05-05 23:30:06,989 ERROR: Exception on /auth/login [GET] [in C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Home\Flask\rr\app\auth\routes.py", line 30, in login
    return render_template('login.html', title='Sign In', form=form)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Home\Flask\rr\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Home\Flask\rr\app\templates\base.html", line 2, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "C:\Users\Home\Flask\rr\app\templates\login.html", line 28, in block 'content'
    <a href="{{ url_for('reset_password_request') }}">Click to Reset!</a>
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'auth.reset_password_request' instead?
2023-05-05 23:30:09,476 ERROR: Exception on /auth/login [GET] [in C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Home\Flask\rr\app\auth\routes.py", line 30, in login
    return render_template('login.html', title='Sign In', form=form)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Home\Flask\rr\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Home\Flask\rr\app\templates\base.html", line 2, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "C:\Users\Home\Flask\rr\app\templates\login.html", line 28, in block 'content'
    <a href="{{ url_for('reset_password_request') }}">Click to Reset!</a>
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'auth.reset_password_request' instead?
2023-05-05 23:52:36,912 INFO: RealtyRadar startup [in C:\Users\Home\Flask\rr\app\__init__.py:64]
